
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import '/imports/plugins/core/accounts/client';
import '/imports/plugins/core/catalog/client';
import '/imports/plugins/core/checkout/client';
import '/imports/plugins/core/dashboard/client';
import '/imports/plugins/core/dom/client';
import '/imports/plugins/core/email/client';
import '/imports/plugins/core/files/client';
import '/imports/plugins/core/hydra-oauth/client';
import '/imports/plugins/core/i18n/client';
import '/imports/plugins/core/layout/client';
import '/imports/plugins/core/orders/client';
import '/imports/plugins/core/payments/client';
import '/imports/plugins/core/router/client';
import '/imports/plugins/core/shipping/client';
import '/imports/plugins/core/taxes/client';
import '/imports/plugins/core/templates/client';
import '/imports/plugins/core/ui/client';
import '/imports/plugins/core/ui-navbar/client';
import '/imports/plugins/core/ui-tagnav/client';
import '/imports/plugins/included/default-theme/client';
import '/imports/plugins/included/discount-codes/client';
import '/imports/plugins/included/email-smtp/client';
import '/imports/plugins/included/marketplace/client';
import '/imports/plugins/included/notifications/client';
import '/imports/plugins/included/payments-example/client';
import '/imports/plugins/included/payments-stripe/client';
import '/imports/plugins/included/product-admin/client';
import '/imports/plugins/included/product-detail-simple/client';
import '/imports/plugins/included/product-variant/client';
import '/imports/plugins/included/search-mongo/client';
import '/imports/plugins/included/shipping-rates/client';
import '/imports/plugins/included/social/client';
import '/imports/plugins/included/ui-search/client';
